import React from 'react';

interface SafeIconProps {
  name: string;
  className?: string;
  size?: number;
}

// Safe icon component that uses emoji fallbacks instead of SVG
const SafeIcon: React.FC<SafeIconProps> = ({ name, className = "", size = 16 }) => {
  const iconMap: Record<string, string> = {
    // Common icons with emoji fallbacks
    'alert-triangle': '⚠️',
    'refresh-cw': '🔄',
    'home': '🏠',
    'user': '👤',
    'settings': '⚙️',
    'mail': '📧',
    'phone': '📞',
    'search': '🔍',
    'menu': '☰',
    'close': '✕',
    'check': '✓',
    'x': '✕',
    'plus': '+',
    'minus': '-',
    'edit': '✏️',
    'delete': '🗑️',
    'save': '💾',
    'upload': '📤',
    'download': '📥',
    'star': '⭐',
    'heart': '❤️',
    'thumbs-up': '👍',
    'thumbs-down': '👎',
    'eye': '👁️',
    'eye-off': '🙈',
    'lock': '🔒',
    'unlock': '🔓',
    'key': '🔑',
    'shield': '🛡️',
    'warning': '⚠️',
    'info': 'ℹ️',
    'success': '✅',
    'error': '❌',
    'loading': '⏳',
    'clock': '🕐',
    'calendar': '📅',
    'folder': '📁',
    'file': '📄',
    'image': '🖼️',
    'video': '🎥',
    'music': '🎵',
    'link': '🔗',
    'external-link': '↗️',
    'arrow-up': '↑',
    'arrow-down': '↓',
    'arrow-left': '←',
    'arrow-right': '→',
    'chevron-up': '⌃',
    'chevron-down': '⌄',
    'chevron-left': '‹',
    'chevron-right': '›',
    'trending-up': '📈',
    'trending-down': '📉',
    'bar-chart': '📊',
    'pie-chart': '🥧',
    'activity': '📊',
    'users': '👥',
    'user-check': '✅👤',
    'user-plus': '👤+',
    'user-minus': '👤-',
    'message-square': '💬',
    'message-circle': '💭',
    'bell': '🔔',
    'bell-off': '🔕',
    'volume-up': '🔊',
    'volume-down': '🔉',
    'volume-off': '🔇',
    'wifi': '📶',
    'wifi-off': '📵',
    'bluetooth': '📶',
    'battery': '🔋',
    'power': '⚡',
    'globe': '🌐',
    'map': '🗺️',
    'location': '📍',
    'camera': '📷',
    'video-camera': '📹',
    'microphone': '🎤',
    'microphone-off': '🎤❌',
    'speaker': '🔊',
    'headphones': '🎧',
    'printer': '🖨️',
    'monitor': '🖥️',
    'smartphone': '📱',
    'tablet': '📱',
    'laptop': '💻',
    'desktop': '🖥️',
    'server': '🖥️',
    'database': '🗄️',
    'cloud': '☁️',
    'cloud-upload': '☁️↑',
    'cloud-download': '☁️↓',
    'wifi-router': '📡',
    'package': '📦',
    'gift': '🎁',
    'shopping-cart': '🛒',
    'shopping-bag': '🛍️',
    'credit-card': '💳',
    'wallet': '👛',
    'dollar-sign': '💲',
    'euro': '💶',
    'pound': '💷',
    'yen': '💴',
    'bitcoin': '₿',
    'building': '🏢',
    'building2': '🏬',
    'trophy': '🏆',
    'medal': '🏅',
    'award': '🏆',
    'flag': '🚩',
    'bookmark': '🔖',
    'tag': '🏷️',
    'share': '📤',
    'share2': '🔗',
    'copy': '📋',
    'paste': '📋',
    'scissors': '✂️',
    'paperclip': '📎',
    'pin': '📌',
    'thumbtack': '📌',
    'magnet': '🧲',
    'compass': '🧭',
    'ruler': '📏',
    'calculator': '🧮',
    'abacus': '🧮',
    'scales': '⚖️',
    'balance': '⚖️',
    'hourglass': '⏳',
    'stopwatch': '⏱️',
    'timer': '⏲️',
    'alarm': '⏰',
    'watch': '⌚',
    'sunrise': '🌅',
    'sunset': '🌇',
    'sun': '☀️',
    'moon': '🌙',
    'star-filled': '⭐',
    'star-empty': '☆',
    'cloud-rain': '🌧️',
    'cloud-snow': '🌨️',
    'cloud-lightning': '⛈️',
    'umbrella': '☂️',
    'thermometer': '🌡️',
    'fire': '🔥',
    'water': '💧',
    'leaf': '🍃',
    'tree': '🌳',
    'flower': '🌸',
    'seedling': '🌱'
  };

  const emoji = iconMap[name] || '❓';

  return (
    <span 
      className={className}
      style={{ 
        fontSize: `${size}px`,
        lineHeight: 1,
        display: 'inline-block',
        verticalAlign: 'middle'
      }}
      role="img"
      aria-label={name}
    >
      {emoji}
    </span>
  );
};

export default SafeIcon;
