import React from 'react';
import { cn } from '@/lib/utils';

// Safe icon components that replace Lucide React icons with emoji fallbacks
// This prevents the "className.includes is not a function" error

interface SafeIconProps {
  className?: string | undefined | null;
  size?: number;
  [key: string]: any;
}

const createSafeIcon = (emoji: string, name: string) => {
  const SafeIcon: React.FC<SafeIconProps> = ({ className, size = 16, ...props }) => {
    const safeClassName = typeof className === 'string' ? className : '';
    return (
      <span 
        className={cn("inline-block", safeClassName)}
        style={{ 
          fontSize: `${size}px`,
          lineHeight: 1,
          display: 'inline-block',
          verticalAlign: 'middle'
        }}
        role="img"
        aria-label={name}
        {...props}
      >
        {emoji}
      </span>
    );
  };
  SafeIcon.displayName = `Safe${name}Icon`;
  return SafeIcon;
};

// Export safe icon components
export const Loader2 = createSafeIcon('⏳', 'Loader2');
export const Search = createSafeIcon('🔍', 'Search');
export const CheckCircle = createSafeIcon('✅', 'CheckCircle');
export const XCircle = createSafeIcon('❌', 'XCircle');
export const Clock = createSafeIcon('🕐', 'Clock');
export const User = createSafeIcon('👤', 'User');
export const Phone = createSafeIcon('📞', 'Phone');
export const MapPin = createSafeIcon('📍', 'MapPin');
export const CreditCard = createSafeIcon('💳', 'CreditCard');
export const Briefcase = createSafeIcon('💼', 'Briefcase');
export const Users = createSafeIcon('👥', 'Users');
export const Eye = createSafeIcon('👁️', 'Eye');
export const EyeOff = createSafeIcon('🙈', 'EyeOff');
export const FileText = createSafeIcon('📄', 'FileText');
export const Shield = createSafeIcon('🛡️', 'Shield');
export const ShieldCheck = createSafeIcon('🛡️✅', 'ShieldCheck');
export const ShieldAlert = createSafeIcon('🛡️⚠️', 'ShieldAlert');
export const ShieldX = createSafeIcon('🛡️❌', 'ShieldX');
export const Lock = createSafeIcon('🔒', 'Lock');
export const Key = createSafeIcon('🔑', 'Key');
export const Database = createSafeIcon('🗄️', 'Database');
export const AlertTriangle = createSafeIcon('⚠️', 'AlertTriangle');
export const RefreshCw = createSafeIcon('🔄', 'RefreshCw');
export const Zap = createSafeIcon('⚡', 'Zap');
export const Upload = createSafeIcon('📤', 'Upload');
export const Camera = createSafeIcon('📷', 'Camera');
export const ArrowLeft = createSafeIcon('←', 'ArrowLeft');
export const Trash2 = createSafeIcon('🗑️', 'Trash2');
export const Filter = createSafeIcon('🔽', 'Filter');
export const Home = createSafeIcon('🏠', 'Home');
export const Settings = createSafeIcon('⚙️', 'Settings');
export const Mail = createSafeIcon('📧', 'Mail');
export const Menu = createSafeIcon('☰', 'Menu');
export const X = createSafeIcon('✕', 'X');
export const Check = createSafeIcon('✓', 'Check');
export const Plus = createSafeIcon('+', 'Plus');
export const Minus = createSafeIcon('-', 'Minus');
export const Edit = createSafeIcon('✏️', 'Edit');
export const Save = createSafeIcon('💾', 'Save');
export const Download = createSafeIcon('📥', 'Download');
export const Star = createSafeIcon('⭐', 'Star');
export const Heart = createSafeIcon('❤️', 'Heart');
export const ThumbsUp = createSafeIcon('👍', 'ThumbsUp');
export const ThumbsDown = createSafeIcon('👎', 'ThumbsDown');
export const Unlock = createSafeIcon('🔓', 'Unlock');
export const Warning = createSafeIcon('⚠️', 'Warning');
export const Info = createSafeIcon('ℹ️', 'Info');
export const Success = createSafeIcon('✅', 'Success');
export const Error = createSafeIcon('❌', 'Error');
export const Loading = createSafeIcon('⏳', 'Loading');
export const Calendar = createSafeIcon('📅', 'Calendar');
export const ChevronDown = createSafeIcon('▼', 'ChevronDown');
export const ChevronUp = createSafeIcon('▲', 'ChevronUp');
export const ChevronLeft = createSafeIcon('◀', 'ChevronLeft');
export const ChevronRight = createSafeIcon('▶', 'ChevronRight');
export const MoreHorizontal = createSafeIcon('⋯', 'MoreHorizontal');
export const MoreVertical = createSafeIcon('⋮', 'MoreVertical');
export const Copy = createSafeIcon('📋', 'Copy');
export const ExternalLink = createSafeIcon('🔗', 'ExternalLink');
export const Link = createSafeIcon('🔗', 'Link');
export const Unlink = createSafeIcon('🔗❌', 'Unlink');
export const Image = createSafeIcon('🖼️', 'Image');
export const Video = createSafeIcon('🎥', 'Video');
export const Music = createSafeIcon('🎵', 'Music');
export const Volume = createSafeIcon('🔊', 'Volume');
export const VolumeOff = createSafeIcon('🔇', 'VolumeOff');
export const Play = createSafeIcon('▶️', 'Play');
export const Pause = createSafeIcon('⏸️', 'Pause');
export const Stop = createSafeIcon('⏹️', 'Stop');
export const SkipForward = createSafeIcon('⏭️', 'SkipForward');
export const SkipBack = createSafeIcon('⏮️', 'SkipBack');
export const FastForward = createSafeIcon('⏩', 'FastForward');
export const Rewind = createSafeIcon('⏪', 'Rewind');
export const Repeat = createSafeIcon('🔁', 'Repeat');
export const Shuffle = createSafeIcon('🔀', 'Shuffle');
export const Bookmark = createSafeIcon('🔖', 'Bookmark');
export const Flag = createSafeIcon('🚩', 'Flag');
export const Tag = createSafeIcon('🏷️', 'Tag');
export const Bell = createSafeIcon('🔔', 'Bell');
export const BellOff = createSafeIcon('🔕', 'BellOff');
export const MessageCircle = createSafeIcon('💬', 'MessageCircle');
export const MessageSquare = createSafeIcon('💬', 'MessageSquare');
export const Send = createSafeIcon('📤', 'Send');
export const Inbox = createSafeIcon('📥', 'Inbox');
export const Archive = createSafeIcon('📦', 'Archive');
export const Package = createSafeIcon('📦', 'Package');
export const Folder = createSafeIcon('📁', 'Folder');
export const FolderOpen = createSafeIcon('📂', 'FolderOpen');
export const File = createSafeIcon('📄', 'File');
export const FileImage = createSafeIcon('🖼️', 'FileImage');
export const FileVideo = createSafeIcon('🎥', 'FileVideo');
export const FileAudio = createSafeIcon('🎵', 'FileAudio');
export const FilePdf = createSafeIcon('📄', 'FilePdf');
export const FileSpreadsheet = createSafeIcon('📊', 'FileSpreadsheet');
export const FileCode = createSafeIcon('📝', 'FileCode');
export const Globe = createSafeIcon('🌐', 'Globe');
export const Wifi = createSafeIcon('📶', 'Wifi');
export const WifiOff = createSafeIcon('📶❌', 'WifiOff');
export const Bluetooth = createSafeIcon('📶', 'Bluetooth');
export const Battery = createSafeIcon('🔋', 'Battery');
export const BatteryLow = createSafeIcon('🪫', 'BatteryLow');
export const Power = createSafeIcon('⚡', 'Power');
export const PowerOff = createSafeIcon('⚡❌', 'PowerOff');
export const Cpu = createSafeIcon('🖥️', 'Cpu');
export const HardDrive = createSafeIcon('💾', 'HardDrive');
export const Monitor = createSafeIcon('🖥️', 'Monitor');
export const Smartphone = createSafeIcon('📱', 'Smartphone');
export const Tablet = createSafeIcon('📱', 'Tablet');
export const Laptop = createSafeIcon('💻', 'Laptop');
export const Printer = createSafeIcon('🖨️', 'Printer');
export const Scanner = createSafeIcon('📠', 'Scanner');
export const Headphones = createSafeIcon('🎧', 'Headphones');
export const Mic = createSafeIcon('🎤', 'Mic');
export const MicOff = createSafeIcon('🎤❌', 'MicOff');
export const Camera2 = createSafeIcon('📸', 'Camera2');
export const CameraOff = createSafeIcon('📷❌', 'CameraOff');
export const Gamepad = createSafeIcon('🎮', 'Gamepad');
export const Joystick = createSafeIcon('🕹️', 'Joystick');
export const Dice = createSafeIcon('🎲', 'Dice');
export const Puzzle = createSafeIcon('🧩', 'Puzzle');
export const Target = createSafeIcon('🎯', 'Target');
export const Trophy = createSafeIcon('🏆', 'Trophy');
export const Medal = createSafeIcon('🏅', 'Medal');
export const Award = createSafeIcon('🥇', 'Award');
export const TrendingUp = createSafeIcon('📈', 'TrendingUp');
export const DollarSign = createSafeIcon('💰', 'DollarSign');
export const Activity = createSafeIcon('📊', 'Activity');
export const AlertCircle = createSafeIcon('⚠️', 'AlertCircle');
export const Wallet = createSafeIcon('👛', 'Wallet');
export const Timer = createSafeIcon('⏱️', 'Timer');
export const Gift = createSafeIcon('🎁', 'Gift');
export const ShoppingCart = createSafeIcon('🛒', 'ShoppingCart');
export const ShoppingBag = createSafeIcon('🛍️', 'ShoppingBag');
export const Store = createSafeIcon('🏪', 'Store');
export const Building = createSafeIcon('🏢', 'Building');
export const Bank = createSafeIcon('🏦', 'Bank');
export const Hospital = createSafeIcon('🏥', 'Hospital');
export const School = createSafeIcon('🏫', 'School');
export const University = createSafeIcon('🏛️', 'University');
export const Church = createSafeIcon('⛪', 'Church');
export const Mosque = createSafeIcon('🕌', 'Mosque');
export const Temple = createSafeIcon('🛕', 'Temple');
export const Synagogue = createSafeIcon('🕍', 'Synagogue');
export const Factory = createSafeIcon('🏭', 'Factory');
export const Warehouse = createSafeIcon('🏬', 'Warehouse');
export const Office = createSafeIcon('🏢', 'Office');
export const Apartment = createSafeIcon('🏠', 'Apartment');
export const House = createSafeIcon('🏡', 'House');
export const Tent = createSafeIcon('⛺', 'Tent');
export const Castle = createSafeIcon('🏰', 'Castle');
export const Stadium = createSafeIcon('🏟️', 'Stadium');
export const Gym = createSafeIcon('🏋️', 'Gym');
export const Pool = createSafeIcon('🏊', 'Pool');
export const Beach = createSafeIcon('🏖️', 'Beach');
export const Mountain = createSafeIcon('⛰️', 'Mountain');
export const Volcano = createSafeIcon('🌋', 'Volcano');
export const Desert = createSafeIcon('🏜️', 'Desert');
export const Forest = createSafeIcon('🌲', 'Forest');
export const Park = createSafeIcon('🏞️', 'Park');
export const Garden = createSafeIcon('🏡', 'Garden');
export const Farm = createSafeIcon('🚜', 'Farm');
export const Field = createSafeIcon('🌾', 'Field');
export const Orchard = createSafeIcon('🍎', 'Orchard');
export const Vineyard = createSafeIcon('🍇', 'Vineyard');
export const Greenhouse = createSafeIcon('🌱', 'Greenhouse');
export const Barn = createSafeIcon('🏚️', 'Barn');
export const Silo = createSafeIcon('🏗️', 'Silo');
export const Windmill = createSafeIcon('🌪️', 'Windmill');
export const Lighthouse = createSafeIcon('🗼', 'Lighthouse');
export const Bridge = createSafeIcon('🌉', 'Bridge');
export const Tunnel = createSafeIcon('🚇', 'Tunnel');
export const Road = createSafeIcon('🛣️', 'Road');
export const Highway = createSafeIcon('🛣️', 'Highway');
export const Railway = createSafeIcon('🛤️', 'Railway');
export const Airport = createSafeIcon('✈️', 'Airport');
export const Seaport = createSafeIcon('⚓', 'Seaport');
export const Harbor = createSafeIcon('🚢', 'Harbor');
export const Marina = createSafeIcon('⛵', 'Marina');
export const Dock = createSafeIcon('🚢', 'Dock');
export const Pier = createSafeIcon('🌊', 'Pier');
export const Jetty = createSafeIcon('🌊', 'Jetty');
export const Wharf = createSafeIcon('🚢', 'Wharf');
export const Quay = createSafeIcon('🚢', 'Quay');
export const Berth = createSafeIcon('⚓', 'Berth');
export const Anchorage = createSafeIcon('⚓', 'Anchorage');
export const Mooring = createSafeIcon('⚓', 'Mooring');
export const Buoy = createSafeIcon('🌊', 'Buoy');
export const Beacon = createSafeIcon('🔦', 'Beacon');
export const Signal = createSafeIcon('🚦', 'Signal');
export const TrafficLight = createSafeIcon('🚦', 'TrafficLight');
export const StopSign = createSafeIcon('🛑', 'StopSign');
export const YieldSign = createSafeIcon('⚠️', 'YieldSign');
export const SpeedLimit = createSafeIcon('🚫', 'SpeedLimit');
export const NoEntry = createSafeIcon('⛔', 'NoEntry');
export const Prohibited = createSafeIcon('🚫', 'Prohibited');
export const Restricted = createSafeIcon('🚫', 'Restricted');
export const Forbidden = createSafeIcon('🚫', 'Forbidden');
export const Banned = createSafeIcon('🚫', 'Banned');
export const Blocked = createSafeIcon('🚫', 'Blocked');
export const Denied = createSafeIcon('🚫', 'Denied');
export const Rejected = createSafeIcon('❌', 'Rejected');
export const Declined = createSafeIcon('❌', 'Declined');
export const Refused = createSafeIcon('❌', 'Refused');
export const Cancelled = createSafeIcon('❌', 'Cancelled');
export const Terminated = createSafeIcon('❌', 'Terminated');
export const Ended = createSafeIcon('❌', 'Ended');
export const Finished = createSafeIcon('✅', 'Finished');
export const Completed = createSafeIcon('✅', 'Completed');
export const Done = createSafeIcon('✅', 'Done');
export const Approved = createSafeIcon('✅', 'Approved');
export const Accepted = createSafeIcon('✅', 'Accepted');
export const Confirmed = createSafeIcon('✅', 'Confirmed');
export const Verified = createSafeIcon('✅', 'Verified');
export const Validated = createSafeIcon('✅', 'Validated');
export const Authenticated = createSafeIcon('✅', 'Authenticated');
export const Authorized = createSafeIcon('✅', 'Authorized');
export const Permitted = createSafeIcon('✅', 'Permitted');
export const Allowed = createSafeIcon('✅', 'Allowed');
export const Granted = createSafeIcon('✅', 'Granted');
export const Enabled = createSafeIcon('✅', 'Enabled');
export const Activated = createSafeIcon('✅', 'Activated');
export const Started = createSafeIcon('▶️', 'Started');
export const Initiated = createSafeIcon('▶️', 'Initiated');
export const Launched = createSafeIcon('🚀', 'Launched');
export const Deployed = createSafeIcon('🚀', 'Deployed');
export const Released = createSafeIcon('🚀', 'Released');
export const Published = createSafeIcon('📢', 'Published');
export const Announced = createSafeIcon('📢', 'Announced');
export const Broadcast = createSafeIcon('📡', 'Broadcast');
export const Transmitted = createSafeIcon('📡', 'Transmitted');
export const Sent = createSafeIcon('📤', 'Sent');
export const Delivered = createSafeIcon('📦', 'Delivered');
export const Received = createSafeIcon('📥', 'Received');
export const Collected = createSafeIcon('📥', 'Collected');
export const Gathered = createSafeIcon('📥', 'Gathered');
export const Assembled = createSafeIcon('🔧', 'Assembled');
export const Built = createSafeIcon('🔨', 'Built');
export const Constructed = createSafeIcon('🏗️', 'Constructed');
export const Created = createSafeIcon('✨', 'Created');
export const Generated = createSafeIcon('✨', 'Generated');
export const Produced = createSafeIcon('🏭', 'Produced');
export const Manufactured = createSafeIcon('🏭', 'Manufactured');
export const Fabricated = createSafeIcon('🔧', 'Fabricated');
export const Crafted = createSafeIcon('🎨', 'Crafted');
export const Designed = createSafeIcon('🎨', 'Designed');
export const Developed = createSafeIcon('💻', 'Developed');
export const Programmed = createSafeIcon('💻', 'Programmed');
export const Coded = createSafeIcon('💻', 'Coded');
export const Scripted = createSafeIcon('📝', 'Scripted');
export const Written = createSafeIcon('✍️', 'Written');
export const Authored = createSafeIcon('✍️', 'Authored');
export const Composed = createSafeIcon('🎼', 'Composed');
export const Arranged = createSafeIcon('🎼', 'Arranged');
export const Orchestrated = createSafeIcon('🎼', 'Orchestrated');
export const Conducted = createSafeIcon('🎼', 'Conducted');
export const Directed = createSafeIcon('🎬', 'Directed');
export const Managed = createSafeIcon('👔', 'Managed');
export const Supervised = createSafeIcon('👔', 'Supervised');
export const Overseen = createSafeIcon('👁️', 'Overseen');
export const Monitored = createSafeIcon('👁️', 'Monitored');
export const Watched = createSafeIcon('👁️', 'Watched');
export const Observed = createSafeIcon('👁️', 'Observed');
export const Inspected = createSafeIcon('🔍', 'Inspected');
export const Examined = createSafeIcon('🔍', 'Examined');
export const Analyzed = createSafeIcon('📊', 'Analyzed');
export const Evaluated = createSafeIcon('📊', 'Evaluated');
export const Assessed = createSafeIcon('📊', 'Assessed');
export const Reviewed = createSafeIcon('📋', 'Reviewed');
export const Audited = createSafeIcon('📋', 'Audited');
export const Tested = createSafeIcon('🧪', 'Tested');
export const Experimented = createSafeIcon('🧪', 'Experimented');
export const Researched = createSafeIcon('🔬', 'Researched');
export const Investigated = createSafeIcon('🔍', 'Investigated');
export const Explored = createSafeIcon('🗺️', 'Explored');
export const Discovered = createSafeIcon('🔍', 'Discovered');
export const Found = createSafeIcon('🔍', 'Found');
export const Located = createSafeIcon('📍', 'Located');
export const Positioned = createSafeIcon('📍', 'Positioned');
export const Placed = createSafeIcon('📍', 'Placed');
export const Installed = createSafeIcon('🔧', 'Installed');
export const Mounted = createSafeIcon('🔧', 'Mounted');
export const Attached = createSafeIcon('📎', 'Attached');
export const Connected = createSafeIcon('🔗', 'Connected');
export const Linked = createSafeIcon('🔗', 'Linked');
export const Joined = createSafeIcon('🔗', 'Joined');
export const United = createSafeIcon('🤝', 'United');
export const Combined = createSafeIcon('🤝', 'Combined');
export const Merged = createSafeIcon('🤝', 'Merged');
export const Integrated = createSafeIcon('🤝', 'Integrated');
export const Synchronized = createSafeIcon('🔄', 'Synchronized');
export const Coordinated = createSafeIcon('🤝', 'Coordinated');
export const Organized = createSafeIcon('📋', 'Organized');
export const Arranged2 = createSafeIcon('📋', 'Arranged2');
export const Structured = createSafeIcon('🏗️', 'Structured');
export const Formatted = createSafeIcon('📄', 'Formatted');
export const Styled = createSafeIcon('🎨', 'Styled');
export const Themed = createSafeIcon('🎨', 'Themed');
export const Customized = createSafeIcon('⚙️', 'Customized');
export const Configured = createSafeIcon('⚙️', 'Configured');
export const Setup = createSafeIcon('⚙️', 'Setup');
export const Initialized = createSafeIcon('🔄', 'Initialized');
export const Prepared = createSafeIcon('📋', 'Prepared');
export const Ready = createSafeIcon('✅', 'Ready');
export const Available = createSafeIcon('✅', 'Available');
export const Online = createSafeIcon('🟢', 'Online');
export const Offline = createSafeIcon('🔴', 'Offline');
export const Connected2 = createSafeIcon('🟢', 'Connected2');
export const Disconnected = createSafeIcon('🔴', 'Disconnected');
export const Active = createSafeIcon('🟢', 'Active');
export const Inactive = createSafeIcon('🔴', 'Inactive');
export const Enabled2 = createSafeIcon('🟢', 'Enabled2');
export const Disabled = createSafeIcon('🔴', 'Disabled');
export const On = createSafeIcon('🟢', 'On');
export const Off = createSafeIcon('🔴', 'Off');
export const Up = createSafeIcon('⬆️', 'Up');
export const Down = createSafeIcon('⬇️', 'Down');
export const Left = createSafeIcon('⬅️', 'Left');
export const Right = createSafeIcon('➡️', 'Right');
export const Forward = createSafeIcon('⏩', 'Forward');
export const Backward = createSafeIcon('⏪', 'Backward');
export const Next = createSafeIcon('⏭️', 'Next');
export const Previous = createSafeIcon('⏮️', 'Previous');
export const First = createSafeIcon('⏮️', 'First');
export const Last = createSafeIcon('⏭️', 'Last');
export const Begin = createSafeIcon('▶️', 'Begin');
export const End = createSafeIcon('⏹️', 'End');
export const Start = createSafeIcon('▶️', 'Start');
export const Finish = createSafeIcon('⏹️', 'Finish');
export const Continue = createSafeIcon('▶️', 'Continue');
export const Resume = createSafeIcon('▶️', 'Resume');
export const Pause2 = createSafeIcon('⏸️', 'Pause2');
export const Stop2 = createSafeIcon('⏹️', 'Stop2');
export const Reset = createSafeIcon('🔄', 'Reset');
export const Restart = createSafeIcon('🔄', 'Restart');
export const Reload = createSafeIcon('🔄', 'Reload');
export const Refresh = createSafeIcon('🔄', 'Refresh');
export const Update = createSafeIcon('🔄', 'Update');
export const Upgrade = createSafeIcon('⬆️', 'Upgrade');
export const Downgrade = createSafeIcon('⬇️', 'Downgrade');
export const Install = createSafeIcon('📥', 'Install');
export const Uninstall = createSafeIcon('🗑️', 'Uninstall');
export const Remove = createSafeIcon('🗑️', 'Remove');
export const Delete = createSafeIcon('🗑️', 'Delete');
export const Erase = createSafeIcon('🗑️', 'Erase');
export const Clear = createSafeIcon('🧹', 'Clear');
export const Clean = createSafeIcon('🧹', 'Clean');
export const Wipe = createSafeIcon('🧹', 'Wipe');
export const Purge = createSafeIcon('🧹', 'Purge');
export const Flush = createSafeIcon('🚽', 'Flush');
export const Empty = createSafeIcon('🗑️', 'Empty');
export const Void = createSafeIcon('⚫', 'Void');
export const Null = createSafeIcon('⚫', 'Null');
export const None = createSafeIcon('⚫', 'None');
export const Zero = createSafeIcon('0️⃣', 'Zero');
export const One = createSafeIcon('1️⃣', 'One');
export const Two = createSafeIcon('2️⃣', 'Two');
export const Three = createSafeIcon('3️⃣', 'Three');
export const Four = createSafeIcon('4️⃣', 'Four');
export const Five = createSafeIcon('5️⃣', 'Five');
export const Six = createSafeIcon('6️⃣', 'Six');
export const Seven = createSafeIcon('7️⃣', 'Seven');
export const Eight = createSafeIcon('8️⃣', 'Eight');
export const Nine = createSafeIcon('9️⃣', 'Nine');
export const Ten = createSafeIcon('🔟', 'Ten');

// Default export for convenience
export default {
  Loader2, Search, CheckCircle, XCircle, Clock, User, Phone, MapPin, CreditCard,
  Briefcase, Users, Eye, EyeOff, FileText, Shield, ShieldCheck, ShieldAlert,
  ShieldX, Lock, Key, Database, AlertTriangle, RefreshCw, Zap, Upload, Camera,
  ArrowLeft, Trash2, Filter, Home, Settings, Mail, Menu, X, Check, Plus, Minus,
  Edit, Save, Download, Star, Heart, ThumbsUp, ThumbsDown, Unlock, Warning,
  Info, Success, Error, Loading, Calendar, ChevronDown, ChevronUp, ChevronLeft,
  ChevronRight, MoreHorizontal, MoreVertical, Copy, ExternalLink, Link, Unlink
};
